# Server configuration
server.port=8080

# NLP Service configuration
nlp.service.url=${PYTHON_NLP_SERVICE_URL:http://localhost:5000}

# File Upload configuration
upload.dir=uploads
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# Static content configuration
spring.web.resources.static-locations=classpath:/static/,file:uploads/
